name: Update Index

on:
  push:
    paths:
      - 'verbali/**/*.pdf'

jobs:
  update_index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get newly added PDF files
        id: new_pdfs
        uses: tj-actions/changed-files@v45
        with:
          files: verbali/**/*.pdf
          json: true
          escape_json: false

      - name: Update HTML with new PDFs
        if: steps.new_pdfs.outputs.added_files != ''
        env:
          ADDED_FILES: ${{ steps.new_pdfs.outputs.added_files }}
        run: |
          echo "$ADDED_FILES" | jq -r '.[]' | while read -r file; do
            python website/autoUpdate.py "$file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain index.html` ]]; then
            git add index.html
            git commit -m "Auto-update index [skip ci]"
            git push
          fi